version: "3"
services:
##redis:
##  ports:
##    - 6379:6379
##  image: redis:latest
  scylla:
    container_name: scylla
    image: scylladb/scylla:5.1.0
    restart: always
    command: --seeds scylla --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
     - 9042:9042
    volumes:
      - "./scylla/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"

# CREATE KEYSPACE venn WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy','DC1' : 1};
